package entities;

public class FinancialTermDefinition {
    private final String debt;
    private final String equity;
    private final String debtToEquity;
    private final String ebitdaMargin;
    private final String revenueGrowth;
    private final String freeCashFlow;
    private final String freeCashFlowMargin;
    private final String freeCashFlowPerShare;
    private final String freeCashFlowYield;

    public FinancialTermDefinition() {
        this.debt = "Debt is something one party owes to another.";
        this.equity = "Equity represents the value that would be returned to shareholders if all assets were liquidated.";
        this.debtToEquity = "Debt to Equity ratio indicates the relative proportion of equity and debt used to finance a company's assets.";
        this.ebitdaMargin = "EBITDA Margin is a measure of a company's operating profit as a percentage of its revenue.";
        this.revenueGrowth = "Revenue Growth is the increase in a company's total revenue or sales over a specific period of time.";
        this.freeCashFlow = "Free Cash Flow (FCF) is the cash a company generates from its operations after deducting capital expenditures necessary to maintain or expand its asset base.";
        this.freeCashFlowMargin = "Free Cash Flow Margin is the percentage of a company's revenue that translates into free cash flow. (FCF/Total Revenue) * 100%";
        this.freeCashFlowPerShare = "Free Cash Flow Per Share is the amount of free cash flow generated by a company for each outstanding share of its common stock.";
        this.freeCashFlowYield = "Free Cash Flow Yield is a company's free cash flow to its market valuation.";
    }

    public String getDebt() {
        return debt;
    }

    public String getEquity() {
        return equity;
    }
    public String getDebtToEquity() {
        return debtToEquity;
    }
    public String getEbitdaMargin() {
        return ebitdaMargin;
    }
    public String getRevenueGrowth() {
        return revenueGrowth;
    }
    public String getFreeCashFlow() {
        return freeCashFlow;
    }
    public String getFreeCashFlowMargin() {
        return freeCashFlowMargin;
    }
    public String getFreeCashFlowPerShare() {
        return freeCashFlowPerShare;
    }

    public String getFreeCashFlowYield() {
        return freeCashFlowYield;
    }
}
